@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana
skinparam handwritten true

actor Slutkunde
participant View as V
participant "OrderController" as C
participant "OrderMapper" as M
participant "CustomerMapper" as CM
participant "MaterialMapper" as MM
participant DB
participant "entity.Customer" as Customer
participant "entity.Order" as O

Slutkunde -> V: Se bestillingsformlar
activate V
V -> C: get request til /bestilling
C --> V: render bestilling.html
deactivate V

Slutkunde -> V: Udfyld bestillingsformular
activate V

V -> C: Post request til /bestilling
activate C
C -> C: Validate form data
C -> Customer: new Customer(data)
activate Customer
Customer --> C: customer object with no id
deactivate Customer
C -> CM: createCustomer(customer object)
activate CM
CM --> DB: execute sql
DB --> CM: generated customer_id
CM --> C: int customerId
deactivate CM
C -> Customer: setCustomerId(customerId)
C -> O: new Order(customer, data)
activate O
O --> C: order object
deactivate O
C -> M: saveOrderToDatabase(order object)
activate M
M --> DB: execute sql
DB --> M: generated order_id
M -> C: int orderId
deactivate M
C -> MM: saveOrderLines(orderId, order.getCarport().getMaterialsList())
activate MM
MM --> DB: execute sql
deactivate MM
C -> C : sæt message attributten til\n success-message eller error-message
C -> V: render kvittering.html med message
deactivate C

deactivate V

@enduml