@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana
skinparam handwritten true

actor Slutkunde
participant View as V
participant "OrderController" as C
participant "OrderMapper" as M
participant DB

Slutkunde -> V: Klikker se tilbud i e-mail
activate V
V -> C: get request til /quote/{id}
C --> V: render setilbud.html
deactivate V

Slutkunde -> V: Trykker godkend tilbud
activate V

V -> C: Post request til /quote/approve
activate C
C -> C: Validate form data
C -> M: approveQuote(id)
activate M
M --> DB: execute sql
M -> C: success/Exception
deactivate M
C -> C : sæt message attributten til\n success-message eller error-message
C -> V: render setilbud.html med message
deactivate C



deactivate V

@enduml