@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana
skinparam handwritten true

actor Sælger
participant View as V
participant "OrderController" as C
participant "OrderMapper" as M
participant DB


Sælger -> V: Se alle ordrer
activate V

V -> C: Get request til /orders
activate C
C -> C: Kontroller brugerrettigheder
C -> M: getOrders()
activate M
M -> DB: execute sql
DB --> M: ordre linjer
M --> C: List<Order> (eller Exception)
deactivate M
C -> C: Gem orderList i ctx.attribute
C -> C: Gem error-message i ctx.attribute
C -> V: render ordreoversigt.html med message
deactivate C

deactivate V

@enduml